version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: lein with-profile test deps
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "project.clj" }}

      - run: lein javac
      - run: lein compile
      - run: lein pom

      - save_cache:
          paths:
            - target
            - pom.xml
          key: built-{{ .Revision }}

      - run: lein coverage
      - run: "bash <(curl -s https://codecov.io/bash)"
  test:
    docker:
      - image: circleci/openjdk:8-jdk@sha256:13389d32dcfc87ca6dc0d15b2becd742385220633627d804687f9b381790d3e4

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - built-{{ .Revision }}
            - m2-{{ checksum "project.clj" }}

      - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
